# Generated by Django 5.0.2 on 2024-02-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("retailer", models.CharField(max_length=255)),
                ("retailer_id", models.IntegerField()),
                ("invoice_date", models.DateField()),
                ("region", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("product", models.CharField(max_length=255)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("units_sold", models.IntegerField()),
                ("total_sales", models.IntegerField()),
                ("operating_profit", models.IntegerField()),
                ("sales_method", models.CharField(max_length=255)),
            ],
        ),
    ]
